name: Install Yarn deps an cache it

runs:
  using: composite
  steps:
    - name: Setup node env 🏗
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn

    - name: Install dependencies 👨🏻‍💻
      shell: bash
      run: cp vidos-config-empty.json vidos-config.json && yarn install --immutable
