name: Install Yarn deps an cache it

runs:
  using: composite
  steps:
    - name: Setup node env 🏗
      uses: actions/setup-node@v2.1.2
      with:
        node-version: ${{ matrix.node }}

    - name: Get yarn cache directory path 🛠
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Cache node_modules 📦
      uses: actions/cache@v3
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-

    - name: Install dependencies 👨🏻‍💻
      shell: bash
      run: cp vidos-config-empty.json vidos-config.json && yarn install
