name: Continuous Integration

on: push

jobs:
  install_cache:
    name: Instal code and deps
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 16

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - uses: ./.github/actions/install

  storybook:
    needs: install_cache
    name: Storybook
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 16

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - uses: ./.github/actions/install

      - name: Install more packages
        run: sudo apt-get install -y ruby fonts-noto

      - name: Build Storybook 👀
        run: yarn build:storybook

      - name: Storycap
        run: |
          STORYCAP_OPS="--serverCmd 'npx --yes -- http-server storybook-static -p 4000'" yarn test:storybook:report || true
          zip -r __screenshots__.zip __screenshots__
          echo "https://gist.github.com/frodrigo/7c470b063ff1efa19022eec2f394319f"

      - name: Export as Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_STORYCAP_REPORT_TOKEN }}
          gist_id: 7c470b063ff1efa19022eec2f394319f
          file_path: __screenshots__.zip
          file_type: binary

      - name: Test Storybook
        run: yarn test:storybook

      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/develop'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
