name: Continuous Integration

on: push

jobs:
  install_cache:
    name: Instal code and deps
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 18

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - uses: ./.github/actions/install

  cypress:
    needs: install_cache
    name: Cypress
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 18

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - uses: ./.github/actions/install

      - name: Install ruby
        run: |
          sudo apt-get install -y ruby &&
          ruby poi_explode.rb cypress/fixtures/teritorio/references/pois.geojson

      - name: yarn build
        run: |
          ln -s ../cypress/fixtures/ static/fixtures &&
          NODE_OPTIONS=--openssl-legacy-provider NODE_ENV=development CONFIG=vidos-config-cypress.json yarn build

      - name: Run Cypress Tests 🧪
        uses: cypress-io/github-action@v5
        env:
          NODE_ENV: development
          CONFIG: vidos-config-cypress.json
        with:
          install-command: yarn --silent
          start: yarn start4cypress
          wait-on: 'http://127.0.0.1:3000'
          wait-on-timeout: 30
